---
title: "AECID TABLAS"
date: "`r format(Sys.Date(), '%d de Diciembre de %Y')`"
output: 
  officedown::rdocx_document:
    reference_docx: !expr system.file('informe_pulso_plantilla.docx', package = 'pulso')
    tables:
      style: Table
      layout: autofit
      width: 1.0
      align: center
      topcaption: true
      caption: 
        style: Table Caption
        pre: "Tabla "
        sep: ": "
        tnd: 0
        tns: '-'
        fp_text: !expr officer::fp_text_lite(bold = TRUE)
    plots:
      style: Normal
      align: center
      topcaption: true
      caption: 
        style: Image Caption
        pre: "Gráfico "
        sep: ": "
        tnd: 0
        tns: '-'
        fp_text: !expr officer::fp_text_lite(bold = TRUE)
    page_size:
      width: 8.3
      height: 11.7
      orient: "portrait"
    page_margins:
      bottom: 0.5
      top: 0.5
      right: 0.2
      left: 0.2
      header: 0.3
      footer: 0.3
      gutter: 0
    reference_num: true
knit: (
  function(inputFile, encoding) {
    rmarkdown::render(
      input = inputFile,
      encoding = encoding,
      output_file = glue::glue("Tablas y significancias_AECID", format(Sys.Date(), '%d.%m.%y'),".docx" )
      )
    }
  )
--- 
```{r setup, include=FALSE}

#configuraciones
if (!require("pacman")) install.packages("pacman")
pacman::p_load(devEMF, knitr)
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE,
                      fig.cap.style = "Image Caption",
                      tab.cap.style = "Table Caption",
                      dev = "emf",
                      fig.ext = "emf")
options(yaml.eval.expr = TRUE)

#paquetes
pacman::p_load(#data tools
                tidyverse, janitor, glue, lubridate, scales, Hmisc,lazyeval, readxl,
                #Gráficos
                plotly, ggrepel, cowplot, grid, fmsb, 
                #importar / exportar
                haven, rio, officer, officedown,
                #Etiquetas
                sjlabelled,
                #tablas
                flextable, knitr, kableExtra, DT, gtsummary, gt,
                #Temas
                ggpubr,
                #Colores
                paletteer, RColorBrewer)

#detach("package:pulso", unload = TRUE)
# pacman::p_load_current_gh("pulsopucp/pulso")
# pacman::p_load_gh(
# # paquete pulso
# "pulsopucp/pulso")

library(pulso)
library(chisq.posthoc.test)
library(dplyr)
library(readxl)
library(labelled)
library(haven)

#Se carga la BD sin etiquetas
ASE <- read_excel("C:\\Users\\Alejandro\\Dropbox\\PULSO_Proyecto_AECID\\ASE_OG.xls", sheet = "Base", skip = 2)
 

#Crear variable combinada de preguntas 40 y 43 sobre NIVEL EDUCATIVO

ASE$premergeNEusted <- ASE$P189_1 #41 nivel educativo ENTREVISTADO
ASE$premergeNEusted[ASE$P191_1 == 3 | ASE$P191_1 == 8 | ASE$P191_1 == 9 ] <- NA

ASE$premergeNEotro <- ASE$P192_1 #44 nivel educativo de la persona que mas aporta (OTRO)
ASE$premergeNEotro[ASE$P191_1 == 1 | ASE$P191_1 == 2] <- NA

ASE$NE_1 <- rowSums(ASE[,c("premergeNEusted", "premergeNEotro")], na.rm=TRUE) #nivel educativo MERGE

#Crear variable combinada de preguntas 41 y 44 sobre SEGUROS DE SALUD

ASE$premergeSSusted <- ASE$P190_1 #41 seguro salud usted
ASE$premergeSSusted[ASE$P191_1 == 3 | ASE$P191_1 == 8 | ASE$P191_1 == 9 ] <- NA

ASE$premergeSSotro <- ASE$P193_1 #44 seguro de salud de la persona que mas aporta (otro)
ASE$premergeSSotro[ASE$P191_1 == 1 | ASE$P191_1 == 2] <- NA

ASE$SS_1 <- rowSums(ASE[,c("premergeSSusted", "premergeSSotro")], na.rm=TRUE) #seguro de salud MERGE

#Eliminar variables mergeadas creadas (4 en total, nos quedamos con las dos generales)

ASE <- ASE[-c(232,233,235,236)]




ASE_1<-
  ASE %>% 
  mutate(
    #Se selecciona las variables de cruce 
    #1.SEXO
    sexo = case_when(
      P10_1 == 1 ~ "Hombre", 
      TRUE ~ "Mujer"),
    
    #2.EDAD
    edad = case_when(
      P11_1 < 30 ~ "18-29", 
      P11_1 >= 30 & P11_1 < 45 ~ "30-44", 
      TRUE ~ "45-70"),
    
    #3.Lima y Regiones
    # #2 casos vacíos
    #norte:CAJAMARCA,LAMBAYEQUE,PIURA,LA LIBERTAD, NORTE =5
    #centro: ANCASH, JUNIN, HUANUCO, HUANCAVELICA, AYACUCHO, ICA =6 
    #sur: AREQUIPA, TACNA, CUSCO, SUR, PUNO = 4
    #oriente: LORETO, UCAYALI, SAN MARTIN =3
    #Lima metropolitana: LIMA, CALLAO = 2
    region = P215_1,
    aregion = factor(case_when(
      region == "CAJAMARCA" | region == "LAMBAYEQUE" | region == "PIURA" | region == "LA LIBERTAD" | region == "NORTE" ~ "Norte", 
      
      region == "AREQUIPA" | region == "TACNA" | region == "CUSCO" | region == "SUR" | region == "PUNO" ~ "Sur", 
      
      region == "ANCASH" | region == "JUNIN" | region == "HUANUCO" | region == "HUANCAVELICA" | region == "AYACUCHO" | region == "ICA" ~ "Centro", 
      
      region == "LORETO" | region == "UCAYALI" | region == "SAN MARTIN" ~ "Oriente", 
      
      region == "LIMA" | region == "CALLAO" ~ "Lima/ Callao", 
      
      TRUE ~ "NS/NR"), 
      
      levels = c ("Norte", "Sur", "Centro", "Oriente", "Lima/ Callao")),
    
    #4.Grado educativo
    #4.1. 189 -> encuestado
    educa1 = factor(case_when(
      P189_1 == 1 | P189_1 == 2 | P189_1 == 3 | P189_1 == 4 ~ "Primaria o menor",
      P189_1 == 5 | P189_1 == 6 ~ "Secundaria",
      P189_1 == 7 | P189_1 == 8 | P189_1 == 9 | P189_1 == 10 ~ "Superior técnica/ Universitaria",
      P189_1 == 11 ~ "Posgrado", 
      TRUE ~ "NS/NR"), 
      levels = c("Primaria o menor", "Secundaria", "Superior técnica/ Universitaria", "Posgrado", "NS/NR")),
    
    
    #4.2. 192 -> educa2 persona que oporta más ingresos (pasará a ser NE_1que se creó arriba - preguntas 40 y 43)
    
    #educa2a -> etiquetas agrupadas sobre NE
    
    #educa2 = as.numeric(P192_1), 
    educa2a = case_when(
      NE_1== 1 ~ "Sin nivel",
      NE_1== 2 ~ "Inicial",
      NE_1== 3 | NE_1== 4 ~ "Primaria",
      NE_1== 5 | NE_1== 6 ~ "Secundaria",
      NE_1== 7 | NE_1== 8 ~ "Superior técnica",
      NE_1== 9 | NE_1== 10 ~ "Superior universitaria",
      NE_1== 11 ~ "Posgrado", 
      TRUE ~ "NS/NR"
    ),
    
    n1 = case_when(
      NE_1== 1 ~ 0,
      NE_1>1 & NE_1<= 5 ~ 2,
      NE_1== 6 ~ 3,
      NE_1== 7 ~ 4, 
      NE_1== 8 ~ 5,
      NE_1== 9 ~ 7,
      NE_1== 10 ~ 9,
      NE_1== 11 ~ 10,
      TRUE ~ 0
    ),
    
    
    #5.Mención de acoso político
    #99
    map = as.numeric(ASE$P99_1),
    mape = factor(case_when(
      map == 1 ~ "Un político hombre",
      map == 2 ~ "Un político mujer",
      map == 3 ~ "Ambos por igual",
      map == 4 ~ "A ninguno",
      TRUE ~ "NS/NR"
    ),
    levels = c("Un político hombre", "Un político mujer", "Ambos por igual", "A ninguno", "NS/NR")),
    
    #NSE
    #N1: educa2p persona que oporta + ingresos #educa2p
    #N2: Para obtener el puntaje de N2 se deben sumar los puntajes asignados a 
    #los artefactos o servicios con los que cuenta el hogar la persona encuestada. #n2
    #P194_1	P195_1	P196_1	P197_1	P198_1	P199_1
    
    art1 = case_when(as.numeric(P194_1) == 1~ 3.5,TRUE~0),
    art2 = case_when(as.numeric(P195_1) == 1~ 3.5,TRUE~0),
    art3 = case_when(as.numeric(P196_1) == 1~ 3.5,TRUE~0),
    art4 = case_when(as.numeric(P197_1) == 1~ 3.5,TRUE~0),
    art5 = case_when(as.numeric(P198_1) == 1~ 3.5,TRUE~0),
    art6 = case_when(as.numeric(P199_1) == 1~ 3.5,TRUE~0),
    
    n2 = rowSums(across(c(art1, art2, art3, art4, art5, art6))),
    
    
    #N3: material predominante de los pisos #n3
    mpp = as.numeric(P188_1),
    
    #aca antes habia un error, mezclaban con educa2
    n3 = case_when(mpp == 1 ~ 9, 
                   mpp == 2 ~ 7, 
                   mpp == 3 ~ 6, 
                   mpp == 4 ~ 3, 
                   mpp == 5 ~ 0, 
                   TRUE ~ 0),
    
    #N4: n°habitaciones / n°personas que viven en el hogar
    #n4 -> 35/#36
    
    # hxm = P35_1/P36_1, #por que dividía estas variables?
    hxm = P184_1/P185_1, 
    
    n4 = case_when(
      hxm >= 1 ~ 5, 
      hxm < 1 & hxm >= 0.75 ~ 4, 
      hxm < 0.75 & hxm >=0.5 ~ 3,
      hxm < 0.5 & hxm >=0.25 ~ 2,
      hxm < 0.25 & hxm > 0 ~ 1,
      TRUE ~ 0),
    
    #n5: seguros de salud del jh (sea el entrevistado u otro)
    
    #ss= as.numeric(P193_1), <- pasará a ser SS_1que se creó arriba - preguntas 41 y 44
    n5 = case_when(
      SS_1== 1 ~ 1, 
      SS_1== 2 ~ 2, 
      SS_1== 3 ~ 2, 
      SS_1== 4 ~ 3, 
      SS_1== 5 ~ 3, 
      SS_1== 6 ~ 4, 
      SS_1== 7 ~ 5, 
      TRUE ~ 0),
    
    ###NSE##
    nsep = rowSums(across(c(n1, n2, n3, n4, n5))),
    
    nse = case_when(
      nsep < 10 ~ "NSE E", 
      nsep >= 10 & nsep < 22 ~ "NSE D", 
      nsep >= 22 & nsep < 26 ~ "NSE C2", 
      nsep >= 26 & nsep < 36 ~ "NSE C1", 
      nsep >= 36 & nsep < 41 ~ "NSE B2", 
      nsep >= 41 & nsep < 46 ~ "NSE B1", 
      nsep >= 46 & nsep < 49 ~ "NSE A2", 
      nsep >= 49 & nsep <= 50 ~ "NSE A1", 
      TRUE ~ "NS/NR"),
    
    nse2 = case_when(
      nsep < 22 ~ "D/E", 
      nsep >= 22 & nsep < 36 ~ "C", 
      nsep >= 36 & nsep <= 50 ~ "A/B", 
      TRUE ~ "NS/NR"),
  ) %>%  
  
  #RENOMBRANDO VARIABLES
  sjlabelled::var_labels(
    sexo = "Sexo",
    edad = "Edad",
    aregion = "Lima y regiones",
    educa1 = "Grado educativo de Encuestado",
    mape = "Mención de acoso político",
    nse2 = "Nivel socio-económico"
  ) %>%  
  
  mutate(
    #ETIQUETAMIENTO Y ORDENAMIENTO DE NIVELES DE VARIABLES
    across(c(P12_1),
           ~ factor(case_when(
             . == 1 ~ "Muy interesado/a", 
             . == 2 ~ "Interesado/a", 
             . == 3 ~ "Poco interesado/a", 
             . == 4 ~ "Nada interesado/a", 
             . == 8 | . == 9 ~ "NS/NR", 
             TRUE ~ "NS/NR"), 
             
             levels = c("Muy interesado/a", "Interesado/a", "Poco interesado/a", "Nada interesado/a","NS/NR"))),
    
    across(c(P13_1),
           ~ factor(case_when(
             . == 1 ~ "Muy informado/a", 
             . == 2 ~ "Informado/a", 
             . == 3 ~ "Poco informado/a", 
             . == 4 ~ "Nada informado/a", 
             . == 8 | . == 9 ~ "NS/NR", 
             TRUE ~ "NS/NR"), 
             
             levels = c("Muy informado/a", "Informado/a", "Poco informado/a", "Nada informado/a", "NS/NR"))),
    
    across(c(P14_1, P15_1, P16_1, P17_1, P18_1, P19_1, P20_1, P21_1, P22_1), 
           ~ factor(case_when(
             . == 1 ~ "Muy de acuerdo", 
             . == 2 ~ "De acuerdo", 
             . == 3 ~ "En desacuerdo", 
             . == 4 ~ "Muy en desacuerdo", 
             . == 8 | . == 9 ~ "NS/NR", 
             TRUE ~ "NS/NR"), 
             
             levels = c("Muy de acuerdo", "De acuerdo", "En desacuerdo", "Muy en desacuerdo","NS/NR"))),
    
    #p23_1 en sintaxis original tenia problemas
    across(c(P23_1), 
           ~ factor(case_when(
             . == 1 ~ "Se puede confiar en la mayoría de las personas", 
             . == 2 ~ "Es muy difícil confiar en los demás", 
             . == 8 | . == 9 ~ "NS/NR", 
             TRUE ~ "NS/NR"), 
             
             levels = c("Se puede confiar en la mayoría de las personas", "Es muy difícil confiar en los demás", "NS/NR"))),
    
    #24 a 34
    across(c(P24_1, P25_1, P26_1, P27_1, P28_1, P29_1, P30_1, P31_1, P32_1, P33_1, P34_1), 
           ~ factor(case_when(
             . == 1 ~ "Mucha", 
             . == 2 ~ "Alguna", 
             . == 3 ~ "Poca", 
             . == 4 ~ "Ninguna", 
             . == 8 | . == 9 ~ "NS/NR", 
             TRUE ~ "NS/NR"), 
             
             levels = c("Mucha", "Alguna", "Poca", "Ninguna","NS/NR"))),
    
    #35-46
    across(c(P35_1, P36_1, P37_1, P38_1, P39_1, P40_1, P41_1, P42_1, P43_1, P44_1, P45_1, P46_1), 
           ~ factor(case_when(
             . == 1 ~ "Sí pertenece", 
             . == 2 ~ "No pertenece", 
             . == 8 | . == 9 ~ "NS/NR", 
             TRUE ~ "NS/NR"), 
             
             levels = c("Sí pertenece", "No pertenece", "NS/NR"))),
    
    #47-56
    across(c(P47_1, P48_1, P49_1, P50_1, P51_1, P52_1, P53_1, P54_1, P55_1, P56_1), 
           ~ factor(case_when(
             . == 1 ~ "Ha hecho", 
             . == 2 ~ "Podría hacer", 
             . == 3 ~ "Nunca lo haría", 
             . == 8 | . == 9 ~ "NS/NR", 
             TRUE ~ "NS/NR"), 
             
             levels = c("Ha hecho", "Podría hacer", "Nunca lo haría","NS/NR"))),
    
    across(c(P57_1), 
           ~ factor(case_when(
             . == 1 ~ "La democracia es preferible a cualquier otra forma de gobierno", 
             . == 2 ~ "A veces un gobierno autoritario o una dictadura puede ser preferible a un gobierno democrático", 
             . == 3 ~ "Me da lo mismo un tipo de gobierno u otro", 
             . == 8 | . == 9 ~ "NS/NR", 
             TRUE ~ "NS/NR"), 
             
             levels = c("La democracia es preferible a cualquier otra forma de gobierno", 
                        "A veces un gobierno autoritario o una dictadura puede ser preferible a un gobierno democrático", 
                        "Me da lo mismo un tipo de gobierno u otro",
                        "NS/NR"))),
    
    across(c(P58_1), 
           ~ factor(case_when(
             . == 1 ~ "Muy satisfecho", 
             . == 2 ~ "Satisfecho", 
             . == 3 ~ "Insatisfecho", 
             . == 4 ~ "Muy insatisfecho", 
             . == 8 | . == 9 ~ "NS/NR", 
             TRUE ~ "NS/NR"), 
             
             levels = c("Muy satisfecho", "Satisfecho", "Insatisfecho", "Muy insatisfecho", "NS/NR"))),
    
    across(c(P59_1), 
           ~ factor(case_when(
             . == 1 ~ "Las listas de candidatos deben presentar intercaladamente candidatos hombres y candidatas mujeres", 
             . == 2 ~ "Las listas de candidatos deben presentar 30% de candidatas mujeres", 
             . == 8 | . == 9 ~ "NS/NR", 
             TRUE ~ "NS/NR"), 
             
             levels = c("Las listas de candidatos deben presentar intercaladamente candidatos hombres y candidatas mujeres", 
                        "Las listas de candidatos deben presentar 30% de candidatas mujeres",
                        "NS/NR"))),
    
    #60-99
    across(c(P60_1, P61_1, P62_1, P63_1, P64_1, P65_1, P66_1, P67_1, P68_1, P69_1, 
             P70_1, P71_1, P72_1, P73_1, P74_1, P75_1, P76_1, P77_1, P78_1, P79_1, 
             P80_1, P81_1, P82_1, P83_1, P84_1, P85_1, P86_1, P87_1, P88_1, P89_1, 
             P90_1, P91_1, P92_1, P93_1, P94_1, P95_1, P96_1, P97_1, P98_1, P99_1), 
           ~ factor(case_when(
             . == 1 ~ "Un político hombre", 
             . == 2 ~ "Una política mujer", 
             . == 3 ~ "Ambos por igual", 
             . == 4 ~ "Ninguno", 
             . == 8 | . == 9 ~ "NS/NR", 
             TRUE ~ "NS/NR"), 
             
             levels = c("Un político hombre", "Una política mujer", "Ambos por igual", "Ninguno","NS/NR"))),
    
    #100-103
    across(c(P100_1, P101_1, P102_1, P103_1), 
           ~ factor(case_when(
             . == 1 ~ "Un hombre", 
             . == 2 ~ "Una mujer", 
             . == 3 ~ "Ambos por igual", 
             . == 4 ~ "Ninguno", 
             . == 8 | . == 9 | . == 99 ~ "NS/NR", 
             TRUE ~ "NS/NR"), 
             
             levels = c("Un hombre", "Una mujer", "Ambos por igual", "Ninguno","NS/NR"))),
    
    #104-106 // 143-145 // 160-169 // 172-181 // 187 // 194-199
    across(c(P104_1, P105_1, P106_1,
             
             P143_1, P144_1, P145_1,
             
             P160_1, P161_1, P162_1, P163_1, P164_1, P165_1, P166_1, P167_1, P168_1, P169_1,
             
             P172_1, P173_1, P174_1, P175_1, P176_1, P177_1, P178_1, P179_1, P180_1, P181_1,
             
             P187_1, P194_1, P195_1, P196_1, P197_1, P198_1, P199_1
    ), 
    ~ factor(case_when(
      . == 1 ~ "Sí", 
      . == 2 ~ "No", 
      . == 8 | . == 9 | . == 99 ~ "NS/NR", 
      TRUE ~ "NS/NR"), 
      
      levels = c("Sí", "No", "NS/NR"))),
    
    #107 -> respuesta multiple
    P107.1 = case_when(P107_1 == 1| P107_2 == 1 ~ "No concordaban con mi posición e ideas políticas",
                       TRUE ~ NA_character_),
    P107.2 = case_when(P107_1 == 2| P107_2 == 2 ~ "No tenían buenas propuestas frente a los problemas que me interesan",
                       TRUE ~ NA_character_),
    P107.3 = case_when(P107_1 == 3| P107_2 == 3 ~ "Por el partido político al que pertenecían",
                       TRUE ~ NA_character_),
    P107.4 = case_when(P107_1 == 4| P107_2 == 4 ~ "No estaban preparadas para ejercer esos cargos",
                       TRUE ~ NA_character_),
    P107.5 = case_when(P107_1 == 5| P107_2 == 5 ~ "No me generaban confianza",
                       TRUE ~ NA_character_),
    P107.6 = case_when(P107_1 == 6| P107_2 == 6 ~ "No tenían posibilidades de ganar",
                       TRUE ~ NA_character_),
    P107.7 = case_when(P107_1 == 7| P107_2 == 7 ~ "No había candidatas mujeres",
                       TRUE ~ NA_character_),
    P107.8 = case_when(P107_1 == 8| P107_2 == 8 ~ "Otra razón",
                       TRUE ~ NA_character_),
    P107.9 = case_when(P107_1 == 88| P107_2 == 99 ~ "NS/NR",
                       TRUE ~ NA_character_),
    P107.10 = case_when(P107_1 == 999| P107_2 == 999 ~ "No Aplica",
                        TRUE ~ NA_character_),
    
    
    #108 -> Otra razón: pregunta abierta
    
    #109
    across(c(P109_1), 
           ~ factor(case_when(
             . == 1 ~ "Por la falta de interés de las mujeres en la política", 
             . == 2 ~ "Por la falta de respaldo de los partidos y agrupaciones políticas", 
             . == 3 ~ "Por la falta de preparación de las mujeres para esos cargos", 
             . == 4 ~ "Porque el electorado prefiere votar por hombres que por mujeres", 
             . == 5 ~ "Otra razón", 
             . == 8 | . == 9 | . == 99 ~ "NS/NR", 
             TRUE ~ NA_character_ ),
             
             levels = c("Por la falta de interés de las mujeres en la política", 
                        "Por la falta de respaldo de los partidos y agrupaciones políticas", 
                        "Por la falta de preparación de las mujeres para esos cargos", 
                        "Porque el electorado prefiere votar por hombres que por mujeres", 
                        "Otra razón", 
                        "NS/NR"))),
    
    #110 -> Otra razón: pregunta abierta
    
    #111-121 // 130-142 // P146_1 // 149-155
    across(c(P111_1, P112_1, P113_1, P114_1, P115_1, P116_1, P117_1, P118_1, P119_1, P120_1, P121_1,
             
             P130_1, P131_1, P132_1, P133_1, P134_1, P135_1, P136_1, P137_1, P138_1, P139_1, P140_1,
             P141_1, P142_1,
             
             P146_1,
             
             P149_1, P150_1, P151_1, P152_1, P153_1, P154_1, P155_1
    ), 
    ~ factor(case_when(
      . == 1 ~ "Muy de acuerdo", 
      . == 2 ~ "De acuerdo", 
      . == 3 ~ "En desacuerdo", 
      . == 4 ~ "Muy en desacuerdo", 
      . == 8 | . == 9 | . == 99 ~ "NS/NR", 
      TRUE ~ "NS/NR"), 
      
      levels = c("Muy de acuerdo", "De acuerdo", "En desacuerdo", "Muy en desacuerdo", "NS/NR"))),
    
    #122
    across(c(P122_1), 
           ~ factor(case_when(
             . == 1 ~ "Mucho más importante para el hombre", 
             . == 2 ~ "Algo más importante para el hombre", 
             . == 3 ~ "Algo más importante para la mujer", 
             . == 4 ~ "Mucho más importante para la mujer",
             . == 5 ~ "Para ambos igual",
             . == 8 | . == 9 ~ "NS/NR", 
             TRUE ~ "NS/NR"), 
             
             levels = c("Mucho más importante para el hombre", 
                        "Algo más importante para el hombre", 
                        "Algo más importante para la mujer", 
                        "Mucho más importante para la mujer", 
                        "Para ambos igual", 
                        "NS/NR"))),
    
    #123-129
    across(c(P123_1, P124_1, P125_1, P126_1, P127_1, P128_1, P129_1), 
           ~ factor(case_when(
             . == 1 ~ "Las mujeres son mucho más apropiadas", 
             . == 2 ~ "Las mujeres son algo más apropiadas", 
             . == 3 ~ "Por igual las mujeres y los hombres", 
             . == 4 ~ "Los hombres son algo más apropiados",
             . == 5 ~ "Los hombres son mucho más apropiados",
             . == 8 | . == 9 ~ "NS/NR", 
             TRUE ~ "NS/NR"), 
             
             levels = c("Las mujeres son mucho más apropiadas", "Las mujeres son algo más apropiadas", "Por igual las mujeres y los hombres", "Los hombres son algo más apropiados", "Los hombres son mucho más apropiados", "NS/NR"))),
    
    #147-148
    across(c(P147_1, P148_1), 
           ~ factor(case_when(
             . == 1 ~ "Mucho", 
             . == 2 ~ "Algo", 
             . == 3 ~ "Poco", 
             . == 4 ~ "Nada",
             . == 8 | . == 9 ~ "NS/NR", 
             TRUE ~ "NS/NR"), 
             
             levels = c("Mucho", "Algo", "Poco", "Nada", "NS/NR"))),
    
    #156-159
    across(c(P156_1, P157_1, P158_1, P159_1), 
           ~ factor(case_when(
             . == 1 ~ "Sí se justifica", 
             . == 2 ~ "No se justifica", 
             . == 8 | . == 9 ~ "NS/NR", 
             TRUE ~ "NS/NR"), 
             
             levels = c("Sí se justifica", "No se justifica", "NS/NR"))),
    
    #170 -> otros: pregunta abierta
    
    #171
    across(c(P171_1), 
           ~ factor(case_when(
             . == 1 ~ "Diario", 
             . == 2 ~ "Varias veces por semana", 
             . == 3 ~ "Semanal", 
             . == 4 ~ "Varias veces al mes",
             . == 5 ~ "Mensual",
             . == 6 ~ "Pocas veces al año",
             . == 8 | . == 9 ~ "NS/NR", 
             TRUE ~ "NS/NR"), 
             
             levels = c("Diario", "Varias veces por semana", "Semanal", "Varias veces al mes", "Mensual", "Pocas veces al año", "NS/NR"))),
    
    #182 -> Otros: pregunta abierta
    
    
    # CREACION DE MÁS VARIABLES
    
    #183 -> respuesta multiple
    
    P183.1 = case_when(P183_1 == 1 |
                         P183_2 == 1 |
                         P183_3 == 1 ~ "Persona y/o familiar",
                       TRUE ~ NA_character_),
    P183.2 = case_when(P183_1 == 2 |
                         P183_2 == 2 |
                         P183_3 == 2 ~ "Laboral/ trabajo", 
                       TRUE ~ NA_character_),
    P183.3 = case_when(P183_1 == 3 |
                         P183_2 == 3 |
                         P183_3 == 3 ~ "Estudios", 
                       TRUE ~ NA_character_),
    P183.4 = case_when(P183_1 == 4 |
                         P183_2 == 4 |
                         P183_3 == 4 ~ "Actividad política/ opiniones políticas",
                       TRUE ~ NA_character_),
    P183.5 = case_when(P183_1 == 5 |
                         P183_2 == 5 |
                         P183_3 == 5 ~ "Actividad pública", 
                       TRUE ~ NA_character_),
    P183.6 = case_when(P183_1 == 6 |
                         P183_2 == 6 |
                         P183_3 == 6 ~ "Activismo social", 
                       TRUE ~ NA_character_),
    P183.7 = case_when(P183_1 == 7 |
                         P183_2 == 7 |
                         P183_3 == 7 ~ "Otros", 
                       TRUE ~ NA_character_),
    P183.8 = case_when(P183_1 == 8 |
                         P183_2 == 8 |
                         P183_3 == 8 |
                         P183_1 == 9 |
                         P183_2 == 9 |
                         P183_3 == 9 ~ "NS/NR", 
                       TRUE ~ NA_character_),
    P183.8 = case_when(P183_1 == 99 |
                         P183_2 == 99 |
                         P183_3 == 99 ~ "No Aplica", 
                       TRUE ~ NA_character_),
    
    
    #184-186: preguntas numéricas
    
    #184, 186
    across(c(P184_1, P186_1), 
           ~ factor(case_when(
             . < 4 ~ "0 a 3", 
             . < 8 ~ "4 a 7", 
             . < 12 ~ "8 a 11", 
             TRUE ~ NA_character_), 
             
             levels = c("0 a 3", "4 a 7", "8 a 11"))),
    
    #185
    across(c(P185_1), 
           ~ factor(case_when(
             . < 6 ~ "0 a 5", 
             . < 11 ~ "6 a 10", 
             . < 16 ~ "11 a 15", 
             TRUE ~ NA_character_), 
             
             levels = c("0 a 5", "6 a 10", "11 a 15"))),
    
    #188
    across(c(P188_1), 
           ~ factor(case_when(
             . == 1 ~ "Parquet o madera pulida y similares; porcelanato, alfombra, mármol", 
             . == 2 ~ "Laminado tipo madera, láminas asfálticas o similares", 
             . == 3 ~ "Losetas / terrazos, mayólicas, cerámicos, vinílicos, mosaico o similares",
             . == 4 ~ "Cemento sin pulir o pulido / madera (entablados)/ tapizón",
             . == 4 ~ "Tierra / otro material (arena y tablones sin pulir)",
             . == 8 | . == 9 ~ "NS/NR",
             TRUE ~ "NS/NR"), 
             
             levels = c("Parquet o madera pulida y similares; porcelanato, alfombra, mármol", 
                        "Laminado tipo madera, láminas asfálticas o similares", 
                        "Losetas / terrazos, mayólicas, cerámicos, vinílicos, mosaico o similares", 
                        "Cemento sin pulir o pulido / madera (entablados)/ tapizón", 
                        "Tierra / otro material (arena y tablones sin pulir)", 
                        "NS/NR"))),
    
    #189 -> variable control (?)
    
    #190,192
    across(c(P190_1, P193_1), 
           ~ factor(case_when(
             . == 1 ~ "Seguro integral de salud (SIS)", 
             . == 2 ~ "Seguro universitario", 
             . == 3 ~ "Seguro escolar privado",
             . == 4 ~ "Essalud",
             . == 5 ~ "Seguro FF.AA./ Policiales",
             . == 6 ~ "Entidad prestadora de salud - EPS",
             . == 7 ~ "Seguro privado de salud",
             . == 8 | . == 88 |. == 99 ~ "NS/NR",
             TRUE ~ "NS/NR"), 
             
             levels = c("Seguro integral de salud (SIS)", 
                        "Seguro universitario", 
                        "Seguro escolar privado", 
                        "Essalud", 
                        "Seguro FF.AA./ Policiales", 
                        "Entidad prestadora de salud - EPS", 
                        "Seguro privado de salud", 
                        "NS/NR"))),
    
    #191: variable irrelevante
    
    #192
    across(c(P192_1), 
           ~ factor(case_when(
             . == 1 | . == 2 ~ "Sin nivel/Inicial",
             . == 3 | . == 4 ~ "Primaria",
             . == 5 | . == 6 ~ "Secundaria",
             . == 7 | . == 8 ~ "Superior técnica",
             . == 9 | . == 10 ~ "Superior universitaria",
             . == 11 ~ "Posgrado",
             . == 88 | . == 99 ~ "NS/NR",
             TRUE ~ "NS/NR"), 
             
             levels = c("Sin nivel/Inicial", 
                        "Primaria", 
                        "Secundaria", 
                        "Superior técnica", 
                        "Superior universitaria", 
                        "Posgrado", 
                        "NS/NR"))),
  )

#Eliminar las respuestas de SÍ la variable P104_1 para casos que nos son del CALLAO

ASE_1$P104_1[ASE_1$P215_1 == "LIMA"] <- NA

#Crear Variable VotoxMujer para eliminar los casos colados en la preguta
#15 o simplemente hacer el código para eliminar (NA) con conectores lógicos
#Elimnar la varaible creada (si se creó)

ASE_1$P107_1[ASE_1$P104_1 == "Sí" | ASE_1$P105_1 == "Sí" | ASE_1$P106_1 == "Sí" ] <- NA
ASE_1$P107_2[ASE_1$P104_1 == "Sí" | ASE_1$P105_1 == "Sí" | ASE_1$P106_1 == "Sí" ] <- NA

```

```{r sintax tabla}

tabla_pulso <-function (data, main_var = NULL, sub_var = NULL, filtrar = TRUE, 
          titulo = titulo1){
  switch_sub_var <- tidyselect::eval_select(enquo(sub_var), 
                                            data[unique(names(data))])
  switch_sub_var <- names(switch_sub_var)
  switch_sub_var <- switch_sub_var %>% table() %>% sum() %>% 
    as.numeric()
  switch_main_var <- tidyselect::eval_select(enquo(main_var), 
                                             data[unique(names(data))])
  switch_main_var <- names(switch_main_var)
  switch_main_var <- switch_main_var %>% table() %>% sum() %>% 
    as.numeric()
  titulo1 <- data %>% select({
    {
      main_var
    }
  }) %>% get_label() %>% unique()
  pop <- data %>% select({
    {
      main_var
    }
  }) %>% names()
  labels <- tibble(numero = if (is.numeric(unlist(sjlabelled::get_values(data[, 
                                                                              pop]), use.names = FALSE))) {
    as.character(unlist(sjlabelled::get_values(data[, pop]), 
                        use.names = FALSE))
  }
  else {
    NA
  }, nombres = unlist(sjlabelled::get_labels(data[pop]), use.names = FALSE), 
  )
  if (switch_main_var == 1 & switch_sub_var == 0) {
    t0 <- data %>% filter({
      {
        filtrar
      }
    }) %>% select({
      {
        main_var
      }
    }) %>% drop_na() %>% mutate(across(everything(), ~replace(., 
                                                              . == 0, NA))) %>% haven::as_factor() %>% mutate(across(everything(), 
                                                                                                                     ~forcats::fct_drop(., labels[labels$numero == 0, 
                                                                                                                     ]$nombres))) %>% gtsummary::tbl_summary(statistic = all_categorical() ~ 
                                                                                                                                                               "{p}% ({n})", digits = list(everything() ~ c(2, 
                                                                                                                                                                                                            0)), missing_text = "No sabe / No responde", label = everything() ~ 
                                                                                                                                                               "") %>% modify_header(label ~ " ") %>% bold_labels() %>% 
      remove_row_type(variables = everything(), type = c("header")) %>% 
      modify_footnote(update = everything() ~ NA) %>% 
      as_flex_table() %>% add_header_lines(titulo) %>% 
      add_footer_lines("% (n) \nFuente: Pulso PUCP") %>% 
      italic(italic = TRUE, part = "header") %>% set_table_properties(layout = "autofit") %>% 
      fontsize(size = 5, part = "all") %>% height(height = 0.75, 
                                                  part = "body")
    t0
  }
  else if (switch_main_var == 1 & switch_sub_var > 0) {
    fn_subtable <- function(data, main, sub) {
      data %>% filter({
        {
          filtrar
        }
      }) %>% dplyr::select({
        {
          main
        }
      }, {
        {
          sub
        }
      }) %>% drop_na() %>% mutate(across(everything(), 
                                         ~replace(., . == 0, NA))) %>% haven::as_factor() %>% 
        mutate(across(everything(), ~forcats::fct_drop(., 
                                                       labels[labels$numero == 0, ]$nombres))) %>% 
        gtsummary::tbl_summary(by = {
          {
            sub
          }
        }, statistic = gtsummary::all_categorical() ~ 
          "{p}% ({n})", digits = list(dplyr::everything() ~ 
                                        c(2, 0)), missing_text = "No sabe / No responde", 
        label = everything() ~ " ") %>% remove_row_type(variables = everything(), 
                                                       type = c("header")) %>% modify_footnote(update = everything() ~ 
                                                                                                 NA)
    }
    main_var <- rlang::enexpr(main_var)
    sub_var <- tidyselect::eval_select(enquo(sub_var), data[unique(names(data))])
    sub_var <- names(sub_var)
    sub_var1 <- rlang::syms(sub_var)
    t0 <- data %>% filter({
      {
        filtrar
      }
    }) %>% dplyr::select({
      {
        main_var
      }
    }) %>% drop_na() %>% mutate(across(everything(), ~replace(., 
                                                              . == 0, NA))) %>% haven::as_factor() %>% mutate(across(everything(), 
                                                                                                                     ~forcats::fct_drop(., labels[labels$numero == 0, 
                                                                                                                     ]$nombres))) %>% gtsummary::tbl_summary(statistic = gtsummary::all_categorical() ~ 
                                                                                                                                                               "{p}% ({n})", digits = list(dplyr::everything() ~ 
                                                                                                                                                                                             c(2, 0)), missing_text = "No sabe / No responde", 
                                                                                                                                                             label = everything() ~ " ") %>% gtsummary::modify_header(label ~ 
                                                                                                                                                                                                                       " ") %>% gtsummary::bold_labels() %>% remove_row_type(variables = everything(), 
                                                                                                                                                                                                                                                                            type = c("header")) %>% modify_footnote(update = everything() ~ 
                                                                                                                                                                                                                                                                                                                      NA)
    sub_tables <- purrr::map(sub_var1, ~fn_subtable(data = data, 
                                                    main = main_var, sub = .x))
    sub_var_labels <- data %>% select(sub_var) %>% get_label()
    tbls <- c(list(t0), sub_tables) %>% gtsummary::tbl_merge(tab_spanner = c("**Total**", 
                                                                             paste0("**", sub_var_labels, "**"))) %>% bold_labels() %>% 
      as_flex_table() %>% add_header_lines(titulo) %>% 
      add_footer_lines("% (n) \nFuente: Pulso PUCP") %>% 
      italic(italic = TRUE, part = "header") %>% set_table_properties(layout = "autofit") %>% 
      fontsize(size = 5, part = "all") %>% height(height = 0.75, 
                                                  part = "body")
    tbls
  }
  else if (switch_main_var > 1 & switch_sub_var == 0) {
    tbl <- data %>% filter({
      {
        filtrar
      }
    }) %>% select({
      {
        main_var
      }
    }) %>% sjlabelled::as_label() %>% gtsummary::tbl_summary(statistic = all_categorical() ~ 
                                                               "{p_nonmiss}% ({n})", digits = list(dplyr::everything() ~ 
                                                                                                     c(2, 0)), missing = "no", label = everything() ~ 
                                                               " ") %>% modify_footnote(update = everything() ~ 
                                                                                         NA) %>% remove_row_type(-1) %>% modify_header(label ~ 
                                                                                                                                         " ") %>% bold_labels() %>% remove_row_type(variables = everything(), 
                                                                                                                                                                                   type = c("header")) %>% as_flex_table() %>% add_header_lines(titulo) %>% 
      add_footer_lines("Fuente: Pulso PUCP") %>% italic(italic = TRUE, 
                                                        part = "header") %>% set_table_properties(layout = "autofit") %>% 
      fontsize(size = 5, part = "all") %>% height(height = 0.75, 
                                                  part = "body")
    tbl
  }
  else if (switch_main_var > 1 & switch_sub_var > 0) {
    fn_subtable <- function(data, main, sub) {
      data %>% filter({
        {
          filtrar
        }
      }) %>% dplyr::select({
        {
          main
        }
      }, {
        {
          sub
        }
      }) %>% sjlabelled::as_label() %>% gtsummary::tbl_summary(by = {
        {
          sub
        }
      }, statistic = all_categorical() ~ "{p_nonmiss}% ({n})", 
      digits = list(dplyr::everything() ~ c(2, 0)), 
      missing = "no", label = everything() ~ " ") %>% 
        modify_footnote(update = everything() ~ NA) %>% 
        remove_row_type(-1) %>% modify_header(label ~ 
                                                " ") %>% bold_labels() %>% remove_row_type(variables = everything(), 
                                                                                          type = c("header"))
    }
    sub_var <- tidyselect::eval_select(enquo(sub_var), data[unique(names(data))])
    sub_var <- names(sub_var)
    sub_var1 <- rlang::syms(sub_var)
    t0 <- data %>% filter({
      {
        filtrar
      }
    }) %>% select({
      {
        main_var
      }
    }) %>% sjlabelled::as_label() %>% gtsummary::tbl_summary(statistic = all_categorical() ~ 
                                                               "{p_nonmiss}% ({n})", digits = list(dplyr::everything() ~ 
                                                                                                     c(2, 0)), missing = "no", label = everything() ~ 
                                                               " ") %>% modify_footnote(update = everything() ~ 
                                                                                         NA) %>% remove_row_type(-1) %>% modify_header(label ~ 
                                                                                                                                         " ") %>% bold_labels() %>% remove_row_type(variables = everything(), 
                                                                                                                                                                                   type = c("header"))
    sub_tables <- purrr::map(sub_var1, ~fn_subtable(data = data, 
                                                    main = main_var, sub = .x))
    sub_var_labels <- data %>% select(sub_var) %>% get_label()
    tbls <- c(list(t0), sub_tables) %>% gtsummary::tbl_merge(tab_spanner = c("**Total**", 
                                                                             paste0("**", sub_var_labels, "**"))) %>% bold_labels() %>% 
      as_flex_table() %>% add_header_lines(titulo) %>% 
      add_footer_lines("% (n) \nFuente: Pulso PUCP") %>% 
      italic(italic = TRUE, part = "header") %>% set_table_properties(layout = "autofit") %>% 
      fontsize(size = 5, part = "all") %>% height(height = 0.75, 
                                                  part = "body")
    tbls
  }
  else {
    return("Error. Necesitas proporcionar al menos una variable.")
  }
}

chisq.posthoc.test1<-function(x){
  chisq.posthoc.test(x) %>% 
    flextable() %>% 
    add_footer_lines("% (n) \nFuente: Pulso PUCP") %>% 
    italic(italic = TRUE, part = "header") %>% 
    set_table_properties(layout = "autofit") %>% 
    fontsize(size = 5, part = "all") %>% 
    height(height = 0.75, part = "body")
}

```


```{r variables cruce}

ASE_1 %>% 
  tabla_pulso(sexo)

ASE_1 %>% 
  tabla_pulso(edad)
salto()

ASE_1 %>% 
  tabla_pulso(aregion) #var recod. pero la original no se recod.

ASE_1 %>% 
  tabla_pulso(educa1) #var recod. pero la original no se recod.
salto()

ASE_1 %>% 
  tabla_pulso(mape) #var recod. la original también recod. pero de la misma manera

ASE_1 %>% 
  tabla_pulso(nse2) #segundo tipo de NSE, el primer tipo tambien esta disponible (nse)
salto()

```

<!---BLOCK_LANDSCAPE_START--->

```{r}
ASE_1 %>% 
  tabla_pulso(P12_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "1. ¿Cuán interesado/a está usted en la política?, ¿está…?")
salto()

ASE_1 %>% 
  tabla_pulso(P13_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "2. En relación con los acontecimientos políticos en el Perú, ¿considera usted que está…?")
salto()

ASE_1 %>% 
  tabla_pulso(P14_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "3.a El voto es la única manera que tiene la gente de influir en política.")
salto()

ASE_1 %>% 
  tabla_pulso(P15_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "3.b Los políticos no se preocupan mucho de lo que piensa la gente.")
salto()

ASE_1 %>% 
  tabla_pulso(P16_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "3.c La gente tiene muy poca influencia en las decisiones del gobierno.")
salto()


ASE_1 %>% 
  tabla_pulso(P17_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "3.d La mayoría de los políticos están en política solo por lo que pueden obtener de ella.")
salto()


ASE_1 %>% 
tabla_pulso(P18_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "3.e Los políticos prometen más de lo que saben que pueden cumplir.")
salto()

ASE_1 %>% 
tabla_pulso(P19_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "3.f Me considero suficientemente preparado/a como para participar en política")
salto()


ASE_1 %>% 
tabla_pulso(P20_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "3.g Siento que podría hacer tan buen trabajo en un cargo público como la mayoría de la gente.")
salto()


ASE_1 %>% 
tabla_pulso(P21_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "3.h Me gustaría encontrar una manera de participar en cuestiones sociales y políticas pero no sé cómo hacerlo.")
salto()


ASE_1 %>% 
tabla_pulso(P22_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "3.i Si los partidos políticos tuvieran procesos más democráticos, sí podría pensar en participar en uno de ellos.")
salto()


ASE_1 %>%
tabla_pulso(P23_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "4. En general, ¿diría usted que se puede confiar en la mayoría de las personas, o en la actualidad, es muy difícil confiar en los demás?")
salto()


ASE_1 %>% 
  tabla_pulso(P24_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "5.a En general ¿usted tiene mucha, alguna, poca o ninguna confianza en las siguientes instituciones...?: El Gobierno Nacional")
salto()


ASE_1 %>% 
  tabla_pulso(P25_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "5.b En general ¿usted tiene mucha, alguna, poca o ninguna confianza en las siguientes instituciones...?: El Congreso de la República")
salto() 


ASE_1 %>% 
  tabla_pulso(P26_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "5.c En general ¿usted tiene mucha, alguna, poca o ninguna confianza en las siguientes instituciones...?: La Iglesia Católica")
salto()


ASE_1 %>% 
  tabla_pulso(P27_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "5.d En general ¿usted tiene mucha, alguna, poca o ninguna confianza en las siguientes instituciones...?: El Poder Judicial")
salto()

ASE_1 %>% 
  tabla_pulso(P28_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "5.e En general ¿usted tiene mucha, alguna, poca o ninguna confianza en las siguientes instituciones...?: Los Medios de Comunicación")
salto()


ASE_1 %>% 
  tabla_pulso(P29_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "5.f En general ¿usted tiene mucha, alguna, poca o ninguna confianza en las siguientes instituciones...?: Los Partidos Políticos")
salto()


ASE_1 %>% 
  tabla_pulso(P30_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "5.g En general ¿usted tiene mucha, alguna, poca o ninguna confianza en las siguientes instituciones...?: Las Fuerzas Armadas")
salto()

ASE_1 %>% 
  tabla_pulso(P31_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "5.h En general ¿usted tiene mucha, alguna, poca o ninguna confianza en las siguientes instituciones...?: Policía nacional del Perú")
salto()


ASE_1 %>% 
  tabla_pulso(P32_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "5.i En general ¿usted tiene mucha, alguna, poca o ninguna confianza en las siguientes instituciones...?: Defensoría del Pueblo")
salto()


ASE_1 %>% 
  tabla_pulso(P33_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "5.j En general ¿usted tiene mucha, alguna, poca o ninguna confianza en las siguientes instituciones...?: Jurado Nacional de Elecciones")
salto()


ASE_1 %>% 
  tabla_pulso(P34_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "5.k En general ¿usted tiene mucha, alguna, poca o ninguna confianza en las siguientes instituciones...?: Oficina Nacional de Procesos Electorales")
salto()


ASE_1 %>% 
  tabla_pulso(P35_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "6.a ¿Pertenece usted a alguna de las siguientes organizaciones?: Club de madres; comedores populares; comités de vaso de leche")
salto()


ASE_1 %>% 
  tabla_pulso(P36_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "6.b ¿Pertenece usted a alguna de las siguientes organizaciones?: Organizaciones religiosas (grupos religiosos o comunidades cristianas u otros)")
salto()


ASE_1 %>% 
  tabla_pulso(P37_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "6.c ¿Pertenece usted a alguna de las siguientes organizaciones?: Asociaciones o gremios profesionales")
salto()


ASE_1 %>% 
  tabla_pulso(P38_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "6.d ¿Pertenece usted a alguna de las siguientes organizaciones?: Asociaciones o gremios empresariales")
salto()


ASE_1 %>% 
  tabla_pulso(P39_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "6.e ¿Pertenece usted a alguna de las siguientes organizaciones?: Asociaciones o gremios de trabajadores - Sindicatos")
salto()


ASE_1 %>% 
  tabla_pulso(P40_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "6.f ¿Pertenece usted a alguna de las siguientes organizaciones?: Organizaciones o asociación de campesinos (rondas)")
salto()

ASE_1 %>% 
  tabla_pulso(P41_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "6.g ¿Pertenece usted a alguna de las siguientes organizaciones?: Asociaciones de Padres de Familia (APAFA)")
salto()


ASE_1 %>% 
  tabla_pulso(P42_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "6.h ¿Pertenece usted a alguna de las siguientes organizaciones?: Asociaciones educativas, artísticas, musicales o culturales")
salto()


ASE_1 %>% 
  tabla_pulso(P43_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "6.i ¿Pertenece usted a alguna de las siguientes organizaciones?: Partidos u organizaciones políticas")
salto()


ASE_1 %>% 
  tabla_pulso(P44_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "6.j ¿Pertenece usted a alguna de las siguientes organizaciones?: Organizaciones vecinales, como juntas y asociaciones de propietarios o asociaciones residenciales")
salto()


ASE_1 %>% 
  tabla_pulso(P45_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "6.k ¿Pertenece usted a alguna de las siguientes organizaciones?: Organizaciones feministas")
salto()


ASE_1 %>% 
  tabla_pulso(P46_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "6.l ¿Pertenece usted a alguna de las siguientes organizaciones?: Organizaciones juveniles")
salto()

```
```{r}
ASE_1 %>% 
  tabla_pulso(P47_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "7.a Me gustaría que me dijera si, en los últimos 5 años ha hecho usted alguna de estas cosas: Participar en marchas o manifestaciones pacíficas")
salto()


ASE_1 %>% 
  tabla_pulso(P48_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "7.b Me gustaría que me dijera si, en los últimos 5 años ha hecho usted alguna de estas cosas: Participar en huelgas")
salto()


ASE_1 %>% 
  tabla_pulso(P49_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "7.c Me gustaría que me dijera si, en los últimos 5 años ha hecho usted alguna de estas cosas: Firmar un comunicado o petición solicitando la atención de demandas sociales")
salto()


ASE_1 %>% 
  tabla_pulso(P50_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "7.d Me gustaría que me dijera si, en los últimos 5 años ha hecho usted alguna de estas cosas: Buscar a periodistas o medios de comunicación para reivindicar demandas (radio, TV, periódico, etc.)")
salto()

ASE_1 %>% 
  tabla_pulso(P51_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "7.e Me gustaría que me dijera si, en los últimos 5 años ha hecho usted alguna de estas cosas: Participar en la toma de oficinas o locales públicos")
salto()

ASE_1 %>% 
  tabla_pulso(P52_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "7.f Me gustaría que me dijera si, en los últimos 5 años ha hecho usted alguna de estas cosas: Bloquear pistas o carreteras")
salto()


ASE_1 %>% 
  tabla_pulso(P53_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "7.g Me gustaría que me dijera si, en los últimos 5 años ha hecho usted alguna de estas cosas: Asistir a reuniones vecinales o comunales")
salto()


ASE_1 %>% 
  tabla_pulso(P54_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "7.h ¿Me gustaría que me dijera si, en los últimos 5 años ha hecho usted alguna de estas cosas: Asistir a algún mitin político o actividades de campaña")
salto()


ASE_1 %>% 
  tabla_pulso(P55_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "7.i Me gustaría que me dijera si, en los últimos 5 años ha hecho usted alguna de estas cosas: Asistir a alguna reunión pública convocada por la municipalidad o alguna autoridad distrital")
salto()



ASE_1 %>% 
  tabla_pulso(P56_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "7.j Me gustaría que me dijera si, en los últimos 5 años ha hecho usted alguna de estas cosas: Participar en redes sociales en internet")
salto()


ASE_1 %>% 
  tabla_pulso(P57_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "8. Ahora le voy a leer algunas opiniones sobre el sistema político en el Perú y quiero que me indique con cuál de esas opiniones está usted más de acuerdo.")
salto()


ASE_1 %>% 
  tabla_pulso(P58_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "9. En general, ¿qué tan satisfecho está usted con el funcionamiento de la democracia en el Perú?")
salto()


ASE_1 %>% 
  tabla_pulso(P59_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "10. ¿Según la ley de paridad y alternancia, que promueve la participación de la mujer…? ")
salto()


ASE_1 %>% 
  tabla_pulso(P60_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "11.a Ahora voy a leer algunas cualidades que puede tener una persona que participa en política y le pediré que me indique a quién caracteriza más esa cualidad ¿a un político hombre, a una política mujer, o a ambos por igual?: Honestidad")
salto()


ASE_1 %>% 
  tabla_pulso(P61_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "11.b Ahora voy a leer algunas cualidades que puede tener una persona que participa en política y le pediré que me indique a quién caracteriza más esa cualidad ¿a un político hombre, a una política mujer, o a ambos por igual?: Buena preparación")
salto()


ASE_1 %>% 
  tabla_pulso(P62_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "11.c Ahora voy a leer algunas cualidades que puede tener una persona que participa en política y le pediré que me indique a quién caracteriza más esa cualidad ¿a un político hombre, a una política mujer, o a ambos por igual?: Responsabilidad y compromiso")
salto()


ASE_1 %>% 
  tabla_pulso(P63_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "11.d Ahora voy a leer algunas cualidades que puede tener una persona que participa en política y le pediré que me indique a quién caracteriza más esa cualidad ¿a un político hombre, a una política mujer, o a ambos por igual?: Seguridad y autoconfianza")
salto()


ASE_1 %>% 
  tabla_pulso(P64_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "11.e Ahora voy a leer algunas cualidades que puede tener una persona que participa en política y le pediré que me indique a quién caracteriza más esa cualidad ¿a un político hombre, a una política mujer, o a ambos por igual?: Firmeza y autoridad")
salto()


ASE_1 %>% 
  tabla_pulso(P65_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "11.f Ahora voy a leer algunas cualidades que puede tener una persona que participa en política y le pediré que me indique a quién caracteriza más esa cualidad ¿a un político hombre, a una política mujer, o a ambos por igual?: Experiencia en gestión y administración")
salto()


ASE_1 %>% 
  tabla_pulso(P66_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "11.g Ahora voy a leer algunas cualidades que puede tener una persona que participa en política y le pediré que me indique a quién caracteriza más esa cualidad ¿a un político hombre, a una política mujer, o a ambos por igual?: Experiencia política")
salto()


ASE_1 %>% 
  tabla_pulso(P67_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "11.h Ahora voy a leer algunas cualidades que puede tener una persona que participa en política y le pediré que me indique a quién caracteriza más esa cualidad ¿a un político hombre, a una política mujer, o a ambos por igual?: Vocación política")
salto()


ASE_1 %>% 
  tabla_pulso(P68_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "11.i Ahora voy a leer algunas cualidades que puede tener una persona que participa en política y le pediré que me indique a quién caracteriza más esa cualidad ¿a un político hombre, a una política mujer, o a ambos por igual?: Carisma")
salto()


ASE_1 %>% 
  tabla_pulso(P69_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "11.j Ahora voy a leer algunas cualidades que puede tener una persona que participa en política y le pediré que me indique a quién caracteriza más esa cualidad ¿a un político hombre, a una política mujer, o a ambos por igual?: Liderazgo")
salto()


ASE_1 %>% 
  tabla_pulso(P70_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "11.k Ahora voy a leer algunas cualidades que puede tener una persona que participa en política y le pediré que me indique a quién caracteriza más esa cualidad ¿a un político hombre, a una política mujer, o a ambos por igual?: Objetivos y metas claras")
salto()

ASE_1 %>% 
  tabla_pulso(P71_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "11.l Ahora voy a leer algunas cualidades que puede tener una persona que participa en política y le pediré que me indique a quién caracteriza más esa cualidad ¿a un político hombre, a una política mujer, o a ambos por igual?: Preocupación y sensibilidad por problemas de la gente")
salto()

```
```{r}
ASE_1 %>% 
  tabla_pulso(P72_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "11.m Ahora voy a leer algunas cualidades que puede tener una persona que participa en política y le pediré que me indique a quién caracteriza más esa cualidad ¿a un político hombre, a una política mujer, o a ambos por igual?: Respeto por las normas y la justicia")
salto()

ASE_1 %>% 
  tabla_pulso(P73_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "11.n Ahora voy a leer algunas cualidades que puede tener una persona que participa en política y le pediré que me indique a quién caracteriza más esa cualidad ¿a un político hombre, a una política mujer, o a ambos por igual?: Capacidad para desarrollar muchas tareas a la vez")
salto()

ASE_1 %>% 
  tabla_pulso(P74_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "11.o Ahora voy a leer algunas cualidades que puede tener una persona que participa en política y le pediré que me indique a quién caracteriza más esa cualidad ¿a un político hombre, a una política mujer, o a ambos por igual?: Capacidad de lucha en el logro de objetivos y metas")
salto()


ASE_1 %>% 
  tabla_pulso(P75_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "11.p Ahora voy a leer algunas cualidades que puede tener una persona que participa en política y le pediré que me indique a quién caracteriza más esa cualidad ¿a un político hombre, a una política mujer, o a ambos por igual?: Agresividad")
salto()


ASE_1 %>% 
  tabla_pulso(P76_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "12.a Del siguiente listado de temas, ¿a quién considera usted que le preocupan más? ¿a un político hombre, a una política mujer, o a ambos por igual?: Salud")
salto()


ASE_1 %>% 
  tabla_pulso(P77_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "12.b Del siguiente listado de temas, ¿a quién considera usted que le preocupan más? ¿a un político hombre, a una política mujer, o a ambos por igual?: Educación")
salto()


ASE_1 %>% 
  tabla_pulso(P78_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "12.c Del siguiente listado de temas, ¿a quién considera usted que le preocupan más? ¿a un político hombre, a una política mujer, o a ambos por igual?: Seguridad ciudadana y delincuencia")
salto()


ASE_1 %>% 
  tabla_pulso(P79_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "12.d Del siguiente listado de temas, ¿a quién considera usted que le preocupan más? ¿a un político hombre, a una política mujer, o a ambos por igual?: Problemas locales y comunitarios")
salto()


ASE_1 %>% 
  tabla_pulso(P80_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "12.e Del siguiente listado de temas, ¿a quién considera usted que le preocupan más? ¿a un político hombre, a una política mujer, o a ambos por igual?: Problemas de justicia")
salto()


ASE_1 %>% 
  tabla_pulso(P81_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "12.f Del siguiente listado de temas, ¿a quién considera usted que le preocupan más? ¿a un político hombre, a una política mujer, o a ambos por igual?: Vivienda")
salto()


ASE_1 %>% 
  tabla_pulso(P82_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "12.g Del siguiente listado de temas, ¿a quién considera usted que le preocupan más? ¿a un político hombre, a una política mujer, o a ambos por igual?: Transporte público")
salto()

ASE_1 %>% 
  tabla_pulso(P83_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "12.h Del siguiente listado de temas, ¿a quién considera usted que le preocupan más? ¿a un político hombre, a una política mujer, o a ambos por igual?: Desempleo")
salto()


ASE_1 %>% 
  tabla_pulso(P84_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "12.i Del siguiente listado de temas, ¿a quién considera usted que le preocupan más? ¿a un político hombre, a una política mujer, o a ambos por igual?: Pobreza y canasta básica")
salto()


ASE_1 %>% 
  tabla_pulso(P85_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "12.j Del siguiente listado de temas, ¿a quién considera usted que le preocupan más? ¿a un político hombre, a una política mujer, o a ambos por igual?: Corrupción")
salto()


ASE_1 %>% 
  tabla_pulso(P86_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "12.k Del siguiente listado de temas, ¿a quién considera usted que le preocupan más? ¿a un político hombre, a una política mujer, o a ambos por igual?: Familia e infancia")
salto()


ASE_1 %>% 
  tabla_pulso(P87_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "12.l Del siguiente listado de temas, ¿a quién considera usted que le preocupan más? ¿a un político hombre, a una política mujer, o a ambos por igual?: Población LGTBQ+")
salto()


ASE_1 %>% 
  tabla_pulso(P88_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "12.m Del siguiente listado de temas, ¿a quién considera usted que le preocupan más? ¿a un político hombre, a una política mujer, o a ambos por igual?: Violencia contra las mujeres")
salto()


ASE_1 %>% 
  tabla_pulso(P89_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "12.n Del siguiente listado de temas, ¿a quién considera usted que le preocupan más? ¿a un político hombre, a una política mujer, o a ambos por igual?: Derechos de las mujeres")
salto()


ASE_1 %>% 
  tabla_pulso(P90_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "12.o Del siguiente listado de temas, ¿a quién considera usted que le preocupan más? ¿a un político hombre, a una política mujer, o a ambos por igual?: Abastecimiento de agua y desagüe")
salto()


ASE_1 %>% 
  tabla_pulso(P91_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "12.p Del siguiente listado de temas, ¿a quién considera usted que le preocupan más? ¿a un político hombre, a una política mujer, o a ambos por igual?: Problemas de medio ambiente")
salto()


ASE_1 %>% 
  tabla_pulso(P92_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "12.q Del siguiente listado de temas, ¿a quién considera usted que le preocupan más? ¿a un político hombre, a una política mujer, o a ambos por igual?: Alimentación")
salto()

ASE_1 %>% 
  tabla_pulso(P93_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "12.r Del siguiente listado de temas, ¿a quién considera usted que le preocupan más? ¿a un político hombre, a una política mujer, o a ambos por igual?: Discriminación contra la mujer")
salto()


ASE_1 %>% 
  tabla_pulso(P94_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "12.s Del siguiente listado de temas, ¿a quién considera usted que le preocupan más? ¿a un político hombre, a una política mujer, o a ambos por igual?: Ausencia de mujeres en el poder")
salto()


ASE_1 %>% 
  tabla_pulso(P95_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "13.a En su opinión, ¿a quién le afecta más? ¿a un político hombre, a una política mujer o a ambos por igual?: La exposición pública")
salto()


ASE_1 %>% 
  tabla_pulso(P96_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "13.b En su opinión, ¿a quién le afecta más? ¿a un político hombre, a una política mujer o a ambos por igual?: La violencia política")
salto()


ASE_1 %>% 
  tabla_pulso(P97_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "13.c En su opinión, ¿a quién le afecta más? ¿a un político hombre, a una política mujer o a ambos por igual?: El desgaste de estar en el poder")
salto()


ASE_1 %>% 
  tabla_pulso(P98_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "13.d En su opinión, ¿a quién le afecta más? ¿a un político hombre, a una política mujer o a ambos por igual?: La pérdida de la vida familiar")
salto()

```
```{r}

ASE_1 %>% 
  tabla_pulso(P100_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "14.a Le voy a leer una lista de características y quiero que usted me diga si usted considera que esa característica es más importante para el éxito político de un hombre, de una mujer o de ambos por igual: Buena apariencia física")
salto()


ASE_1 %>% 
  tabla_pulso(P101_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "14.b Le voy a leer una lista de características y quiero que usted me diga si usted considera que esa característica es más importante para el éxito político de un hombre, de una mujer o de ambos por igual: Respaldo de un partido político")
salto()


ASE_1 %>% 
  tabla_pulso(P102_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "14.c Le voy a leer una lista de características y quiero que usted me diga si usted considera que esa característica es más importante para el éxito político de un hombre, de una mujer o de ambos por igual: Buena preparación")
salto()


ASE_1 %>% 
  tabla_pulso(P103_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "14.d Le voy a leer una lista de características y quiero que usted me diga si usted considera que esa característica es más importante para el éxito político de un hombre, de una mujer o de ambos por igual: Carácter fuerte y agresivo")
salto()


ASE_1 %>% 
  tabla_pulso(P104_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "15.a En las recientes elecciones regionales y municipales del 2 de octubre, ¿Votó usted por una candidata mujer…?: CALLAO Y CIUDADES DEL INTERIOR: Para gobernadora regional")
salto()


ASE_1 %>% 
  tabla_pulso(P105_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "15.b En las recientes elecciones regionales y municipales del 2 de octubre, ¿Votó usted por una candidata mujer…?: Para alcaldesa provincial")
salto()

ASE_1 %>% 
  tabla_pulso(P106_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "15.c En las recientes elecciones regionales y municipales del 2 de octubre, ¿Votó usted por una candidata mujer…?: Para alcaldesa distrital")
salto()

```
```{r}
#107

ASE_1 %>% 
  filter(!is.na(P107_1))  %>%
  tabla_pulso(starts_with("P107."), c(sexo, edad, aregion, educa1, mape, nse2), titulo = "16. ¿Por qué no votó por una candidata mujer? Por favor, indique una o dos razones que usted considere más importantes.")
salto()

```
```{r}
ASE_1 %>% 
  tabla_pulso(P109_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "17.1 ¿Por qué cree que hay tan pocas mujeres en los gobiernos regionales? Por favor, indique solo una razón, la principal.")
salto()


ASE_1 %>% 
  tabla_pulso(P111_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "18.a ¿Podría decirme si está Ud. muy de acuerdo, de acuerdo, en desacuerdo o muy en desacuerdo con cada una de las frases que le voy a leer?: Una madre que trabaja puede tener con sus hijos una relación tan cálida y estable como una madre que no trabaja")
salto()


ASE_1 %>% 
  tabla_pulso(P112_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "18.b ¿Podría decirme si está Ud. muy de acuerdo, de acuerdo, en desacuerdo o muy en desacuerdo con cada una de las frases que le voy a leer?: Es probable que a un niño en edad prescolar le perjudique que su madre trabaje")
salto()


ASE_1 %>% 
  tabla_pulso(P113_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "18.c ¿Podría decirme si está Ud. muy de acuerdo, de acuerdo, en desacuerdo o muy en desacuerdo con cada una de las frases que le voy a leer?: Cuando la mujer tiene un trabajo a jornada completa, la vida familiar se perjudica")
salto()


ASE_1 %>% 
  tabla_pulso(P114_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "18.d ¿Podría decirme si está Ud. muy de acuerdo, de acuerdo, en desacuerdo o muy en desacuerdo con cada una de las frases que le voy a leer?: Trabajar está bien, pero lo que la mayoría de las mujeres realmente quiere es formar un hogar y tener hijos")
salto()


ASE_1 %>% 
  tabla_pulso(P115_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "18.e ¿Podría decirme si está Ud. muy de acuerdo, de acuerdo, en desacuerdo o muy en desacuerdo con cada una de las frases que le voy a leer?: Ser ama de casa es tan gratificante como trabajar por un salario")
salto()

ASE_1 %>% 
  tabla_pulso(P116_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "18.f ¿Podría decirme si está Ud. muy de acuerdo, de acuerdo, en desacuerdo o muy en desacuerdo con cada una de las frases que le voy a leer?: El deber de un hombre es ganar dinero; el deber de una mujer es cuidar de su casa y su familia")
salto()

ASE_1 %>% 
  tabla_pulso(P117_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "18.g ¿Podría decirme si está Ud. muy de acuerdo, de acuerdo, en desacuerdo o muy en desacuerdo con cada una de las frases que le voy a leer?: Una madre sola puede criar a un hijo tan bien como el padre y la madre juntos")
salto()


ASE_1 %>% 
  tabla_pulso(P118_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "18.h ¿Podría decirme si está Ud. muy de acuerdo, de acuerdo, en desacuerdo o muy en desacuerdo con cada una de las frases que le voy a leer?: Un padre solo puede criar a un hijo tan bien como el padre y la madre juntos")
salto()


ASE_1 %>% 
  tabla_pulso(P119_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "18.i ¿Podría decirme si está Ud. muy de acuerdo, de acuerdo, en desacuerdo o muy en desacuerdo con cada una de las frases que le voy a leer?: Una pareja de mujeres lesbianas puede criar a un hijo tan bien como una pareja de hombre y mujer")
salto()


```
```{r}

ASE_1 %>% 
  tabla_pulso(P120_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "18.j ¿Podría decirme si está Ud. muy de acuerdo, de acuerdo, en desacuerdo o muy en desacuerdo con cada una de las frases que le voy a leer?: Una pareja de hombres homosexuales puede criar a un hijo tan bien como una pareja de hombre y mujer")
salto()


ASE_1 %>% 
  tabla_pulso(P121_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "18.k ¿Podría decirme si está Ud. muy de acuerdo, de acuerdo, en desacuerdo o muy en desacuerdo con cada una de las frases que le voy a leer?: Las mujeres que participan en política descuidan el hogar")
salto()


ASE_1 %>% 
  tabla_pulso(P122_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "19. ¿Diría usted que seguir estudios superiores es…? ")
salto()


ASE_1 %>% 
  tabla_pulso(P123_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "20.a Las personas pueden tener diferentes opiniones acerca de si las mujeres o los hombres son más apropiados para ocupar ciertos puestos de liderazgo. Por favor, para cada uno de los siguientes puestos, indique cuál es la respuesta que se acerca más a su propia opinión: Ministro o ministra de estado")
salto()


ASE_1 %>% 
  tabla_pulso(P124_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "20.b Las personas pueden tener diferentes opiniones acerca de si las mujeres o los hombres son más apropiados para ocupar ciertos puestos de liderazgo. Por favor, para cada uno de los siguientes puestos, indique cuál es la respuesta que se acerca más a su propia opinión: Rector o rectora de una universidad")
salto()


ASE_1 %>% 
  tabla_pulso(P125_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "20.c Las personas pueden tener diferentes opiniones acerca de si las mujeres o los hombres son más apropiados para ocupar ciertos puestos de liderazgo. Por favor, para cada uno de los siguientes puestos, indique cuál es la respuesta que se acerca más a su propia opinión: Alto ejecutivo o ejecutiva de una gran empresa")
salto()

ASE_1 %>% 
  tabla_pulso(P126_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "20.d Las personas pueden tener diferentes opiniones acerca de si las mujeres o los hombres son más apropiados para ocupar ciertos puestos de liderazgo. Por favor, para cada uno de los siguientes puestos, indique cuál es la respuesta que se acerca más a su propia opinión: Gobernador o gobernadora regional")
salto()


ASE_1 %>% 
  tabla_pulso(P127_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "20.e Las personas pueden tener diferentes opiniones acerca de si las mujeres o los hombres son más apropiados para ocupar ciertos puestos de liderazgo. Por favor, para cada uno de los siguientes puestos, indique cuál es la respuesta que se acerca más a su propia opinión: Alcalde o alcaldesa provincial")
salto()


ASE_1 %>% 
  tabla_pulso(P128_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "20.f Las personas pueden tener diferentes opiniones acerca de si las mujeres o los hombres son más apropiados para ocupar ciertos puestos de liderazgo. Por favor, para cada uno de los siguientes puestos, indique cuál es la respuesta que se acerca más a su propia opinión: Alcalde o alcaldesa distrital")
salto()


ASE_1 %>% 
  tabla_pulso(P129_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "20.g Las personas pueden tener diferentes opiniones acerca de si las mujeres o los hombres son más apropiados para ocupar ciertos puestos de liderazgo. Por favor, para cada uno de los siguientes puestos, indique cuál es la respuesta que se acerca más a su propia opinión: Presidente o presidenta de la República")
salto()


ASE_1 %>% 
  tabla_pulso(P130_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "21.a ¿Qué tan de acuerdo o en desacuerdo estaría usted con las siguientes medidas para alcanzar la equidad de género?: Cuotas o cantidades mínimas para aumentar el número de puestos para mujeres en el gobierno")
salto()


ASE_1 %>% 
  tabla_pulso(P131_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "21.b ¿Qué tan de acuerdo o en desacuerdo estaría usted con las siguientes medidas para alcanzar la equidad de género?: Cuotas o cantidades mínimas para aumentar el número de vacantes para mujeres en las universidades")
salto()


ASE_1 %>% 
  tabla_pulso(P132_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "21.c ¿Qué tan de acuerdo o en desacuerdo estaría usted con las siguientes medidas para alcanzar la equidad de género?: Cuotas o cantidades mínimas para aumentar el número de mujeres en posiciones gerenciales.")
salto()


ASE_1 %>% 
  tabla_pulso(P133_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "22.a Con relación a las siguientes afirmaciones, diga usted si está de acuerdo o en desacuerdo: Está bien que un hombre golpee a su pareja, si ella no quiere tener relaciones sexuales con él.")
salto()


ASE_1 %>% 
  tabla_pulso(P134_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "22.b Con relación a las siguientes afirmaciones, diga usted si está de acuerdo o en desacuerdo: Una mujer debe tolerar la violencia de su pareja para mantener a su familia unida.")
salto()


ASE_1 %>% 
  tabla_pulso(P135_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "22.c Con relación a las siguientes afirmaciones, diga usted si está de acuerdo o en desacuerdo: Hay ocasiones en que las mujeres merecen ser golpeadas.")
salto()


ASE_1 %>% 
  tabla_pulso(P136_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "22.d Con relación a las siguientes afirmaciones, diga usted si está de acuerdo o en desacuerdo: Está bien que la mujer denuncie a la policía por los actos de agresión de su pareja.")
salto()


ASE_1 %>% 
  tabla_pulso(P137_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "22.e Con relación a las siguientes afirmaciones, diga usted si está de acuerdo o en desacuerdo: Cuando una mujer es violada, por lo general ella lo provocó.")
salto()


ASE_1 %>% 
  tabla_pulso(P138_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "22.f Con relación a las siguientes afirmaciones, diga usted si está de acuerdo o en desacuerdo: Si una mujer no se defiende físicamente, no se puede decir que fue violación.")
salto()


ASE_1 %>% 
  tabla_pulso(P139_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "23.a Hablando ahora de las leyes y políticas públicas para enfrentar la violencia contra la mujer en el país ¿Qué tan de acuerdo estaría usted con las siguientes afirmaciones?: En la educación de niños y adolescentes es importante que se incorpore el enfoque de género, es decir que hombres y mujeres tengan igualdad de oportunidades, derechos y deberes.")
salto()


ASE_1 %>% 
  tabla_pulso(P140_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "23.b Hablando ahora de las leyes y políticas públicas para enfrentar la violencia contra la mujer en el país ¿Qué tan de acuerdo estaría usted con las siguientes afirmaciones?: Tal como están, las leyes no proporcionan suficiente protección a las víctimas de violencia.")
salto()


ASE_1 %>% 
  tabla_pulso(P141_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "23.c Hablando ahora de las leyes y políticas públicas para enfrentar la violencia contra la mujer en el país ¿Qué tan de acuerdo estaría usted con las siguientes afirmaciones?: Tal como están, las leyes son muy duras para los hombres.")
salto()


ASE_1 %>% 
  tabla_pulso(P142_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "23.d Hablando ahora de las leyes y políticas públicas para enfrentar la violencia contra la mujer en el país ¿Qué tan de acuerdo estaría usted con las siguientes afirmaciones?: Tal como están, las leyes hacen que para las mujeres sea muy fácil presentar cargos por violencia contra los hombres.")
salto()


ASE_1 %>% 
  tabla_pulso(P143_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "24.a Ahora quisiera saber si usted: ¿Ha escuchado de alguna campaña o actividad en su lugar residencia o de trabajo que trate sobre prevención de la violencia hacia las mujeres?")
salto()


ASE_1 %>% 
  tabla_pulso(P144_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "24.b Ahora quisiera saber si usted: ¿Está a favor de la Estrategia Nacional de prevención de la violencia hacia las mujeres?")
salto()


ASE_1 %>% 
  tabla_pulso(P145_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "24.c Ahora quisiera saber si usted: ¿Se considera usted una persona feminista?")
salto()


ASE_1 %>% 
  tabla_pulso(P146_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "25. ¿Qué tan de acuerdo o en desacuerdo está usted con las campañas de prevención de la violencia hacia las mujeres?")
salto()


ASE_1 %>% 
  tabla_pulso(P147_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "26. Con relación a los avances en la equidad de género, ¿usted diría que en el país se ha avanzado… ")
salto()


ASE_1 %>% 
  tabla_pulso(P148_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "27. Y con relación a la prevención de la violencia contra la mujer, ¿usted diría que en el país se ha avanzado…")
salto()


ASE_1 %>% 
  tabla_pulso(P149_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "28.a Con relación a las siguientes afirmaciones, diga usted si está de acuerdo o en desacuerdo con cada una: Un hombre de verdad es el que manda.")
salto()

```
```{r}

ASE_1 %>% 
  tabla_pulso(P150_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "28.b Con relación a las siguientes afirmaciones, diga usted si está de acuerdo o en desacuerdo con cada una: Un hombre de verdad es el que defiende su reputación con la fuerza si es necesario.")
salto()


ASE_1 %>% 
  tabla_pulso(P151_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "28.c Con relación a las siguientes afirmaciones, diga usted si está de acuerdo o en desacuerdo con cada una: Un hombre de verdad es el que tiene la última palabra en las decisiones mimportantes del hogar.")
salto()


#151 no está completa la oración en la BD

ASE_1 %>% 
  tabla_pulso(P152_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "28.d Con relación a las siguientes afirmaciones, diga usted si está de acuerdo o en desacuerdo con cada una: Un hombre de verdad es el que sólo tiene relaciones sexuales con mujeres.")
salto()


ASE_1 %>% 
  tabla_pulso(P153_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "28.e Con relación a las siguientes afirmaciones, diga usted si está de acuerdo o en desacuerdo con cada una: Un hombre de verdad no tendría un amigo homosexual.")
salto()


ASE_1 %>% 
  tabla_pulso(P154_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "28.f Con relación a las siguientes afirmaciones, diga usted si está de acuerdo o en desacuerdo con cada una: Un hombre de verdad no se comporta como una mujer.")
salto()


ASE_1 %>% 
  tabla_pulso(P155_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "28.g Con relación a las siguientes afirmaciones, diga usted si está de acuerdo o en desacuerdo con cada una: Un hombre de verdad se avergonzaría de tener un hijo homosexual.")
salto()


ASE_1 %>% 
  tabla_pulso(P156_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "29.a ¿En cuáles de las siguientes situaciones que voy a leer justificaría usted que un hombre reaccione con violencia hacia un hombre homosexual?: Si un hombre homosexual insiste en coquetearle o seducirle")
salto()


ASE_1 %>% 
  tabla_pulso(P157_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "29.b ¿En cuáles de las siguientes situaciones que voy a leer justificaría usted que un hombre reaccione con violencia hacia un hombre homosexual?: Si un hombre homosexual no despega su mirada de él (cuando lo mira fijamente).")
salto()


ASE_1 %>% 
  tabla_pulso(P158_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "29.c ¿En cuáles de las siguientes situaciones que voy a leer justificaría usted que un hombre reaccione con violencia hacia un hombre homosexual?: Si un hombre homosexual se está besando en la boca con otro hombre en público.")
salto()


ASE_1 %>% 
  tabla_pulso(P159_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "29.d ¿En cuáles de las siguientes situaciones que voy a leer justificaría usted que un hombre reaccione con violencia hacia un hombre homosexual?: Si un hombre homosexual actúa de una manera afeminada.")
salto()


ASE_1 %>% 
  tabla_pulso(P160_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "30.a Ahora me gustaría preguntarle sobre algunos aspectos de sus relaciones familiares. Quisiera que indique usted, cuando era niño/a y adolescente: Fue golpeado(a) o castigado(a) físicamente por sus padres u otros adultos en su hogar.")
salto()


ASE_1 %>% 
  tabla_pulso(P161_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "30.b Ahora me gustaría preguntarle sobre algunos aspectos de sus relaciones familiares. Quisiera que indique usted, cuando era niño/a y adolescente: Fue insultado(a) o humillado(a) por alguien de su familia en frente de otras personas.")
salto()


ASE_1 %>% 
  tabla_pulso(P162_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "30.c Ahora me gustaría preguntarle sobre algunos aspectos de sus relaciones familiares. Quisiera que indique usted, cuando era niño/a y adolescente: Vio o escuchó que su madre fue golpeada por su padre o pareja.")
salto()


ASE_1 %>% 
  tabla_pulso(P163_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "30.d Ahora me gustaría preguntarle sobre algunos aspectos de sus relaciones familiares. Quisiera que indique usted, cuando era niño/a y adolescente: Fue testigo de 'lorneo' o 'mariconeo' de niños o adolescentes hombres en su escuela o en su barrio.")
salto()


ASE_1 %>% 
  tabla_pulso(P164_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "30.e Ahora me gustaría preguntarle sobre algunos aspectos de sus relaciones familiares. Quisiera que indique usted, cuando era niño/a y adolescente: Fue testigo de que el 'lorneo' o 'mariconeo' de niños o adolescentes hombres terminó en violencia física en su escuela o en su barrio.")
salto()


ASE_1 %>% 
  tabla_pulso(P165_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "31.a Ahora quisiera que me cuente si es usted usuario de las siguientes redes sociales: Facebook")
salto()


ASE_1 %>% 
  tabla_pulso(P166_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "31.b Ahora quisiera que me cuente si es usted usuario de las siguientes redes sociales: Twitter")
salto()


ASE_1 %>% 
  tabla_pulso(P167_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "31.c Ahora quisiera que me cuente si es usted usuario de las siguientes redes sociales: Instagram")
salto()


ASE_1 %>% 
  tabla_pulso(P168_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "31.d Ahora quisiera que me cuente si es usted usuario de las siguientes redes sociales: Tik tok")
salto()

ASE_1 %>% 
  tabla_pulso(P170_cod_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "31.f Ahora quisiera que me cuente si es usted usuario de las siguientes redes sociales: Whatsapp")
salto() #cambiar


ASE_1 %>% 
  tabla_pulso(P169_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "31.e Ahora quisiera que me cuente si es usted usuario de las siguientes redes sociales: Otros")
salto()


#170 - Pregunta abierta

ASE_1 %>% 
  tabla_pulso(P171_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "32. ¿Con qué frecuencia comparte algún tipo de contenido en sus perfiles de redes sociales?")
salto()


ASE_1 %>% 
  tabla_pulso(P172_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "33.a ¿Alguna vez usted ha sufrido los siguientes tipos de violencia en las redes sociales?: Ha recibido amenazas y extorsión")
salto()


ASE_1 %>% 
  tabla_pulso(P173_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "33.b ¿Alguna vez usted ha sufrido los siguientes tipos de violencia en las redes sociales?: Han publicado información sobre su vida privada sin su consentimiento")
salto()


ASE_1 %>% 
  tabla_pulso(P174_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "33.c ¿Alguna vez usted ha sufrido los siguientes tipos de violencia en las redes sociales?: Han subido videos o fotos comprometedoras")
salto()


ASE_1 %>% 
  tabla_pulso(P175_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "33.d ¿Alguna vez usted ha sufrido los siguientes tipos de violencia en las redes sociales?: Han hackeado sus cuentas o han publicado perfiles falsos suyos")
salto()


ASE_1 %>% 
  tabla_pulso(P176_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "33.e ¿Alguna vez usted ha sufrido los siguientes tipos de violencia en las redes sociales?: Se han dirigido campañas de desprestigio o maltrato contra usted")
salto()


ASE_1 %>% 
  tabla_pulso(P177_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "33.f ¿Alguna vez usted ha sufrido los siguientes tipos de violencia en las redes sociales?: Ha sido víctima de acoso sexual")
salto()


ASE_1 %>% 
  tabla_pulso(P178_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "33.g ¿Alguna vez usted ha sufrido los siguientes tipos de violencia en las redes sociales?: Han lanzado mensajes agresivos contra usted referidos a su imagen corporal")
salto()


ASE_1 %>% 
  tabla_pulso(P179_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "33.h ¿Alguna vez usted ha sufrido los siguientes tipos de violencia en las redes sociales?: Han lanzado mensajes agresivos contra usted referidos a tu capacidad intelectual")
salto()


ASE_1 %>% 
  tabla_pulso(P180_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "33.i ¿Alguna vez usted ha sufrido los siguientes tipos de violencia en las redes sociales?: Han lanzado mensajes agresivos contra usted referidos a su color de piel, raza o etnia")
salto()


ASE_1 %>% 
  tabla_pulso(P181_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "33.j ¿Alguna vez usted ha sufrido los siguientes tipos de violencia en las redes sociales?: Otros")
salto()


#182: pregunta abierta

```
```{r} 

#183

ASE_1 %>% 
  filter(!is.na(P183_1))  %>%
  tabla_pulso(starts_with("P183."), c(sexo, edad, aregion, educa1, mape, nse2), titulo = "34. En qué ámbito de su vida se ha presentado la violencia en redes? Puede señalar más de un ámbito de su vida.")
salto()

```
```{r}
ASE_1 %>% 
  tabla_pulso(P184_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "35. ¿Cuántas habitaciones tiene en su hogar que actualmente use exclusivamente para dormir (incluida la de servicio doméstico)?")
salto()


ASE_1 %>% 
  tabla_pulso(P185_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "36. ¿Cuántas personas viven permanentemente en el hogar (sin incluir servicio doméstico)?")
salto()


ASE_1 %>% 
  tabla_pulso(P186_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "37. ¿Cuántos hijos tiene o ha tenido Ud.? SI NO HA TENIDO NINGUNO COLOCAR CERO “0”.")
salto()

ASE_1 %>% 
  tabla_pulso(P187_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "38. ¿Convive Ud. en pareja en la actualidad?")
salto()

ASE_1 %>% 
  tabla_pulso(P188_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "39. ¿El material predominante en los pisos de su vivienda es…?")
salto()


ASE_1 %>% 
  tabla_pulso(P190_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "41. ¿El sistema de prestación de seguro de salud al cual está afiliado usted es…?")
salto()


ASE_1 %>% 
  tabla_pulso(P192_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "43. ¿Cuál es el nivel de instrucción de la persona que aporta más ingresos a su hogar?")
salto()


ASE_1 %>% 
  tabla_pulso(P193_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "44. ¿El sistema de prestación de seguro de salud al cual está afiliada la persona que aporta más ingresos a su hogar es…? ")
salto()

ASE_1 %>% 
  tabla_pulso(P194_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "45.a Usted en su hogar, ¿cuenta con alguno de los siguientes bienes, artefactos o servicios?: Computadora o laptop en funcionamiento")
salto()


ASE_1 %>% 
  tabla_pulso(P195_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "45.b Usted en su hogar, ¿cuenta con alguno de los siguientes bienes, artefactos o servicios?: Refrigeradora/Congeladora en funcionamiento")
salto()


ASE_1 %>% 
  tabla_pulso(P196_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "45.c Usted en su hogar, ¿cuenta con alguno de los siguientes bienes, artefactos o servicios?: Lavadora en funcionamiento")
salto()

ASE_1 %>% 
  tabla_pulso(P197_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "45.d Usted en su hogar, ¿cuenta con alguno de los siguientes bienes, artefactos o servicios?: Horno microondas en funcionamiento")
salto()

ASE_1 %>% 
  tabla_pulso(P198_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "45.e Usted en su hogar, ¿cuenta con alguno de los siguientes bienes, artefactos o servicios?: Teléfono fijo en funcionamiento")
salto()


ASE_1 %>% 
  tabla_pulso(P199_1, c(sexo, edad, aregion, educa1, mape, nse2), titulo = "45.f Usted en su hogar, ¿cuenta con alguno de los siguientes bienes, artefactos o servicios?: Conexión a Internet")
salto()

```

<!---BLOCK_LANDSCAPE_STOP--->
